### ISSUE TITLE
Only single digit "papers," (that is numbers 1-9) can be pulled off 3 and 4 digit numbers.

### ISSUE THREAD

**Issue by bethstade** [phetsims/making-tens#38]
Triple and 4 digit numbers should not allow "10"s to be broken up.
Only single digits as "papers," the numbers 1-9 should pull off these numbers.
When a 3 or 4 digit has a multiple of the ten on it, the entire multiple should come off when the upper right touch area is activated. 
In the picture below, the top is line is correct way to break apart, the bottom line should not happen.
<img width="894" alt="screen shot 2015-09-18 at 6 15 44 am" src="https://cloud.githubusercontent.com/assets/5370001/9959007/d5b332f6-5dcc-11e5-926a-6529f7af6939.png">

**Comment by amanda-phet** [comment]
@bethstade can you edit this incomplete sentence in your comment above to clarify what it means (I don't understand it myself and we want to be sure it's clear to @AshrafSharf ):  

>Only single digits as "papers," the numbers 1-9 should pull off these numbers.

**Comment by AshrafSharf** [comment]
Fixed. Please Check it

**Comment by amanda-phet** [comment]
This seems to be working for me but I'll let @bethstade take a closer look.

**Comment by bethstade** [comment]
Looks great. thanks.

**Comment by bethstade** [comment]
It appears this is still an issue with 4 digit numbers and 100.
A similar logic should apply.  When I pull from the top right of 1400 I should get 1300 and 100.
Ones should not come off.
It does seem correct on 1000 - Pulling from top right on 1000 gives me 900 and 100.
This logic should continue when we have the 1000 numbers.  So if you pull from top right of 3000 you should get 2900 and 100.

**Comment by AshrafSharf** [comment]
Fixed it. Please verify.

**Comment by bethstade** [comment]
Looks good.

**Comment by amanda-phet** [comment]
Looks good to me too.

**Comment by jonathanolson** [comment]
Currently for the number 111, I can pull the 100 off. Is that the desired behavior?

**Comment by bethstade** [comment]
yes.  pulling off the 100 is correct. similarly you can pull a ten off of 11.
